

all:

small:
	# convert vhv-view-of-r588-with-colours.jpg -resize 413 vhv-view-of-r588-with-colours-small.jpg
	# convert polyphony.jpg -resize 413 polyphony-small.jpg
	#convert banff.jpg -resize 413x -gravity center -crop 413x259+0+0 +repage banff-small.jpg
	convert headphones.svg -resize 431x259 -background white -gravity center -extent 431x259 headphones-small.png







download:
	#wget --no-check-certificate "https://upload.wikimedia.org/wikipedia/commons/2/25/Polyphony.JPG" 
	# mv Polyphony.JPG z.jpg && mv z.jpg polyphony.jpg
	#wget --no-check-certificate "https://upload.wikimedia.org/wikipedia/commons/0/05/Kinnear_Centre_at_Banff_Centre.jpg" -O banff.jpg
	#wget --no-check-certificate "https://upload.wikimedia.org/wikipedia/commons/b/b9/Headphones_%281292150%29_-_The_Noun_Project.svg" -O headphones.svg
